# Generated by Django 3.1.5 on 2021-04-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('address', models.CharField(default='', max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='customers/')),
            ],
        ),
    ]
