# Generated by Django 3.1.5 on 2021-03-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20210325_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contact',
            new_name='contato',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='quantitade',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_type',
            new_name='tipo_de_produto',
        ),
        migrations.AddField(
            model_name='customer',
            name='endereço',
            field=models.CharField(default='', max_length=150),
        ),
    ]
